# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test
  pod 'TKSubmitTransition', :git => 'https://github.com/entotsu/TKSubmitTransition.git'
  pod 'GradientAnimator', '~> 1.3.1'
  pod 'MarqueeLabel'
  pod 'WCLShineButton'

end
